include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: warning
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:

    # ───── STYLE & READABILITY ─────
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true

    unnecessary_this: true
    use_key_in_widget_constructors: true

    # ───── SAFETY & BEST PRACTICES ─────
    avoid_init_to_null: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true

    # ───── CLEAN CODE ─────
    avoid_print: true
    unnecessary_new: true
    unnecessary_const: true
    curly_braces_in_flow_control_structures: true

    # ───── PERFORMANCE ─────
    prefer_final_locals: true
    prefer_final_fields: true

    # ───── FLUTTER SPECIFIC ─────
    sized_box_for_whitespace: true
    use_colored_box: true
    use_decorated_box: true
